import Head from 'next/head'
import styles from '@/styles/Info.module.scss'
import TopMenu from '@/components/TopMenu'
import Footer from '@/components/Footer'

function term() {
  return (
    <>
      <TopMenu />
      <div className={styles.one}>
        <h1>Terms & Conditions</h1>
        <p>

          As the original purchaser of content sold on rankboost, you are entitled to access and use the content which is identified in the course and which is on the rankboost website, at rankboost.live ("Website"). In order to access and use this content, you must register with rankboost and create a password to use in accessing the content on the Website.<br /><br /><br />

          Your password is unique and exclusive to you, and you may not transfer your password to any other person or allow any other person to use your password to access or use content on the Website. You agree to notify rankboost immediately if any other person makes unauthorized use of your password. rankboost reserves the right to suspend or revoke your password in the event of any misuse of your password or any use of your password in violation of these Terms and Conditions. In the event of any such suspension or revocation, you will not be entitled to any refund or payment.<br /><br /><br />

          These Terms of Use govern your access to and use of the Website and the content on the Website. By accessing and using the Website, you agree to these Terms of Use. If you do not agree to any of these Terms of Use, you may not access or use the site. rankboost reserves the right to modify these Terms of Use at any time and in its sole discretion. Your use of the site following any modification will constitute your assent to and acceptance of the modifications.<br /><br /><br />

          Upon registration, rankboost grants you a non-exclusive, non-transferable, non-assignable, personal license to access and use the rankboost content identified in the content you purchased via an online/offline reader. You also agree to allow us to send you emails about new product launches, updates, etc. using the email you have signed up on the app/website with.<br /><br /><br />

          rankboost will not be liable for any delay or interruption in your access to the site or any content located on the site, or for any transmission errors, equipment or software incompatibilities, force majeure or other failure of performance. rankboost will use reasonable efforts to correct any failure of performance, but rankboost will not be required to make any changes to any equipment or software used by rankboost or its contractors or agents to ensure compatibility with any equipment or software used by you. You may not use the site or the content on the site for any commercial purpose, including but not limited to the use of any of the content to market or sell goods or services to any person. You agree not to launch any automated system, including without limitation, "robots," "spiders," or "offline readers," to access the site.<br /><br /><br />

          rankboost reserves the right to change, suspend access to, or remove any or all of the content on the Website at any time, for any reason, in its sole discretion. rankboost also reserves the right to discontinue the Website at any time, either temporarily or permanently. In the event of the removal of any content from the Website or the termination of the Website, you will not be entitled to any refund or payment. If you are involved in pirating the content or doing any harm to the firm in any form, we can remove your access with no refund whatsoever along with legal action as suitable.<br /><br /><br />

          YOU AGREE THAT YOUR USE OF THE SITE SHALL BE AT YOUR SOLE RISK, AND RANKBOOST WILL NOT BE HELD LIABLE IN ANY WAY FOR YOUR USE OF THE SITE OR FOR ANY INFORMATION CONTAINED ON THE SITE. ALL CONTENT CONTAINED IN OR REFERRED TO ON THE SITE IS PROVIDED "AS IS," WITHOUT ANY REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY LAW, rankboost DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. rankboost MAKES NO WARRANTIES THAT THE SITE WILL BE ERROR-FREE, OR THAT ANY ERRORS WILL BE CORRECTED, OR THAT THE SITE OR THE SERVER FROM WHICH THE SITE IS OPERATED WILL BE FREE OF VIRUSES OR OTHER POTENTIALLY HARMFUL CODES. UNDER NO CIRCUMSTANCES, INCLUDING NEGLIGENCE, SHALL rankboost BE HELD LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES AND EXPENSES OF ANY KIND (INCLUDING, WITHOUT LIMITATION, PERSONAL INJURY OR PROPERTY DAMAGE, LOST PROFITS, AND DAMAGES ARISING FROM COMPUTER VIRUSES, BUSINESS INTERRUPTION, LOST DATA, UNAUTHORIZED ACCESS TO OR USE OF SITE SERVERS OR ANY PERSONAL INFORMATION STORED THEREIN, OR ANY INTERRUPTION OR CESSATION OF OPERATION OF THE SITE) ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF THE SITE OR ANY INFORMATION CONTAINED ON THE SITE, WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.<br /><br /><br />

          You agree to indemnify, hold harmless and defend rankboost from and against any and all claims, damages, losses, liabilities, judgments, awards, settlements, costs and expenses (including attorney &quot;s fees and court costs) arising out of or resulting from your use of this Website or the violation by you of any of these Terms of Use. We will be sending emails to you related to preparation advice if you sign up. You consent giving us your email address for this reason.<br /><br /><br />

          YOU AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THIS SITE OR YOUR USE OF THIS SITE MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, AND WILL THEREAFTER BE PERMANENTLY BARRED.<br /><br /><br />

          Referral/Affiliate Terms:The money or currency can be transferred to your bank account if you agree with our referral policy and create referral account. rankboost Credits are a legal or transferrable currency and can only be used to avail discounts within the rankboost platform only.Any legal/informal disputes arising between users due to the credits will not be a responsiblity of rankboost. The affiliate/referral program is in a beta stage and may be discontinued at any point in future.We can change the rules, commision rates and maximum discounts applicable at any point. You understand that we are a private company and might change (increase or decrease) the affiliate/referral commisions, value of a credit, or any other rules based on how they are helping us grow.We will try to keep the program alive for as long as possible to help our affiliates, but it is recommended to use your credits as soon as possible in case the rules change in future (we will try our best to keep your commisions high, but due to uncertainity of running a company, we can &quot;t promise anything). If misuse of the policy is seen (fake accounts, credit transfers in any form, using bots/own accounts (with same IP) then we can reduce or remove your credits completely. A removal from courses might also be observed. The credits/referral system is by no means a right and the privilege for which might be removed from an account if needed or required.<br /><br /><br />

          These Terms of Use constitute the entire agreement between you and rankboost concerning your use of the Website and the contents of the Website. If any provision is deemed invalid by a court of competent jurisdiction, the remaining provisions shall remain in full force and effect. No waiver of any the Terms of Use shall be deemed a further or continuing waiver of such term or condition or any other term or condition, and any failure by rankboost to assert any right or provision under these Terms of Use shall not constitute a waiver of such right or provision.<br /><br /><br />
        </p>
      </div>
      <Footer />
    </>)
}

export default term